#!/bin/sh
export $(cat ~/.env | xargs)

xrandr -d :0 --output eDP-1 --auto --primary
xrandr -d :0 --output DP-2-1 --off --output DP-2-2 --off

# re-scale background
grep feh ~/.i3/config | sed "s/exec //" | sh

killall -9 play
killall -9 pulseaudio
pulseaudio -D

$HOME/get_sinks 'Analog' > ~/.i3/audio_device
pactl set-default-sink `cat $HOME/.i3/audio_device`
pactl set-sink-mute `cat $HOME/.i3/audio_device` 1
pactl set-sink-volume `cat $HOME/.i3/audio_device` 0

xmodmap ~/.Xmodmap

sudo /usr/local/sbin/dock_off

xset -b
