#!/bin/sh
export $(cat ~/.env | xargs)

xrandr -d :0 --dpi 80 --output eDP-1 --off --output DP-2-2 --mode 1920x1200 --primary --output DP-2-1 --auto --same-as DP-2-2 --panning "1920x1200*"
#xrandr -d :0 --output DP-2-2 --primary
#xrandr -d :0 --dpi 80

# re-scale background
grep feh ~/.i3/config | sed "s/exec //" | sh

sudo /usr/local/sbin/dock_on


killall -9 play
killall -9 pulseaudio


# things which take time to recognize devices ...
sleep 2.5

pulseaudio -D

# turn off and on 7.1 profile
pactl set-card-profile alsa_card.pci-0000_00_03.0 off
wanted_profile=$(pactl list cards | grep output:hdmi-surround71 | grep "available: yes" | grep -v active | tr -d '\t' | cut -d ' ' -f1 | rev | cut -c2- | rev)
pactl set-card-profile alsa_card.pci-0000_00_03.0 $wanted_profile

# always play non-hearable sound to prevent av decoder to turn off
play -n -c1 synth sin gain -100 > /dev/null 2>&1 &

$HOME/get_sinks 'Digital' > ~/.i3/audio_device
pactl set-default-sink `cat $HOME/.i3/audio_device`
pactl set-sink-mute `cat $HOME/.i3/audio_device` 0
pactl set-sink-volume `cat $HOME/.i3/audio_device` 100%

numlockx on
setxkbmap us,de -option grp:switch
xmodmap $HOME/.Xmodmap

xset -b
xset s off
xset -dpms
