#!/bin/zsh
# zsh is required for context sensitive shell expansion

systemctl stop netctl-auto@wlp3s0.service &
netctl start ethernet-static

# disable powertop usb tunings
echo 'on' > /sys/bus/usb/devices/*/power/control

# remove old traces from wlp* interface
rm /var/run/resolvconf/interfaces/wlp*
resolvconf -u
