#!/bin/zsh
# zsh is required for context sensitive shell expansion

systemctl stop netctl-auto@wlp3s0.service &
netctl start ethernet-static

# disable powertop usb tunings
echo 'on' > /sys/bus/usb/devices/*/power/control

echo nameserver 192.168.2.2 > /etc/resolv.conf
